### ISSUE TITLE
App irregularly crashes in the OrderedLogger

### ISSUE THREAD

**Issue by seijikun** [simpleLoc/SensorReadoutApp#1]
The app irregularly crashes in `OrderedLogger` while recording, with the following exception:
```
2020-05-28 11:18:07.778 13027-13078/de.fhws.indoor.sensorreadout E/AndroidRuntime: FATAL EXCEPTION: ReorderThread
    Process: de.fhws.indoor.sensorreadout, PID: 13027
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:740)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:477)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:402)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:209)
        at java.util.Arrays.sort(Arrays.java:1325)
        at java.util.Collections.sort(Collections.java:169)
        at de.fhws.indoor.sensorreadout.loggers.OrderedLogger$ReorderBuffer$ReorderThread.run(OrderedLogger.java:205)
```

**Comment by seijikun** [comment]
First attempt at fixing the issue.
It seems, the comparison between `LogEntry` objects was too simple - it didn't handle the case of equal timestamps.
Using Java's comparison method for longs instead of rolling our own, now.
